### PR TITLE
Allow logging setup on logger instances

### PR DESCRIPTION
**Pull request by joshwlewis**
Heyo!

I'm using logrus's`logrus.New()` to create logger instances rather than using the imported singleton logger. The method signatures are a bit different between the two, and it looks like rollrus is only supporting the singleton version.

This adds some new methods (that have parity with the singleton version) that allow consumers to setup rollbar on those logrus Logger instances.

What do you think, @apg, @freeformz?

### CODE REVIEW

**Comment by freeformz** [comment]
I'd rather we make a rollrus.NewHook() so that you can add it like other hooks via Logger.Hooks.Add()

**Comment by joshwlewis** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ND75GXGz&#x2F;1801-iteration-2-sprettur-rollbar-reporting"> Iteration 2: Sprettur rollbar reporting</a>

**Comment by freeformz** [comment]
LGTM: FWIW, we should probably move the examples from the README into an ExampleXXXX function in the _test.go file so that it's compile time checked for validity.

**Comment by joshwlewis** [comment]
Cool, thanks. TIL: GoDoc examples.

**Pull request merged**
